# Generated by Django 5.0.7 on 2024-07-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_useremail_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='selleremail',
        ),
    ]
